# Generated by Django 3.2.7 on 2021-10-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRecord',
            fields=[
                ('query', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SentimentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.DecimalField(decimal_places=3, max_digits=4)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment_extraction_app.queryrecord')),
            ],
        ),
    ]
